### ISSUE TITLE
How to start in "legacy" Two-Pane view, without 3-Way shown?

### ISSUE THREAD

**Issue by Blake-LeBlanc** [whiteinge/diffconflicts#17]
Hello!
Now that 3-way diffs have been added, how do we set it up so that it starts in the "legacy" viewmode with only two panes showing?

Here's what I have in my .gitconfig
`[merge]
	tool = diffconflicts`

`[mergetool "diffconflicts"]
	cmd = vim -c DiffConflicts \"$MERGED\" \"$BASE\" \"$LOCAL\" \"$REMOTE\"
	trustExitCode = true`

`[mergetool]
	keepBackup = false`

Here's how it initially looks upon start: 
https://imgur.com/a/s4h8812

And here's how it looks after entering `:DiffConflicts`:
https://imgur.com/a/Bs2Wd3W

Is there any way to start the mergetool with the upper "3-way" portion hidden and just show the side-by-side view as outlined in your youtube video?

Thanks again for such a great diff viewmode!
-Blake

**Comment by whiteinge** [comment]
Hm, that two-pane view should still be the default view -- no configuration changes needed. The recent addition was an opt-in that wrapped existing functionality.

That first screenshot looks like Git is opening the default Vimdiff mergetool rather than the diffconflicts mergetool. Your configuration looks correct so something else must be going sideways.

Below are a few troubleshooting guesses. Sorry for the basic ones but hopefully it's better to err on the side of being thorough 😝.

1. Double-check the `.gitconfig` syntax and also look for duplicate or conflicting `[merge]` and `[mergetool]` entries elsewhere in the file.
2. Also make sure the `.gitconfig` file is still in the expected location in your home directory.
3. Try invoking the different mergetools manually: `git mergetool -t vimdiff` and `git mergetool -t diffconflicts` to see if the first works as expected and that the second works at all.
4. Look for any error messages after Vim loads with `:messages`.
5. Double-check you're running the current version of diffconflicts (2.1.0) and that updating it via whatever plugin manager you're using finished successfully. The recent changes are all addition-only changes but it's definitely possible that I missed something.

Good luck! Please let me know if you find the problem (or not).

**Comment by Blake-LeBlanc** [comment]
Thank you for your quick and detailed reply Seth, that helped put me on the right track!  Turns out it was something on my end, now it's back in action. 

I ran `$ git config --global --list` and saw that somehow, the project's local `.git/config` file was altered to overwrite the --global mergetool settings. Once I removed that line, everything worked like charm.

Thanks again!
