### ISSUE TITLE
Error when running DiffConflictsShowHistory

### ISSUE THREAD

**Issue by jeremymarc** [whiteinge/diffconflicts#5]
Getting an error when running the command : DiffConflictsShowHistory from nvim:
https://www.dropbox.com/s/1val0bbzhpr9uuw/Screenshot%202018-07-24%2020.46.14.png?dl=0

Am I missing something?

Thanks

**Comment by whiteinge** [comment]
Hm. How was nvim invoked? This plugin needs to be invoked via the Git mergetool machinery so that those other versions of the file are available. Instructions here: https://github.com/whiteinge/diffconflicts#installation (And the end-result should look like this: https://github.com/whiteinge/dotfiles/blob/68635bad1d49c7d9ce2fe28938bc5700c3df65e7/.gitconfig#L170-L172)

(Side note: Although now that you mention it, there's no reason I couldn't make this also work for directly editing a file with conflict markers. I think that would be a good addition...)

If you did invoke the script via Git's mergetool, perhaps nvim does something slightly different than Vim. If so, will you please paste the output of `:ls` ?

**Comment by whiteinge** [comment]
I've added some error handling around this that will hopefully help. If not, please feel free to reopen.
